Fix -Wimplicit-function-declaration
libtom/libtompoly pull request #4
Opened 2022-10-19 01:22 UTC by thesamesam

Causes build failures with Clang 16.

Bug: https://bugs.gentoo.org/875527
Signed-off-by: Sam James <sam@gentoo.org>

2022-11-05 06:16 UTC, thesamesam commented
@sjaeckel could you possibly take a look? thanks

2022-11-05 16:59 UTC, sjaeckel requested changes
Sorry, I completely missed this PR!

PR looks fine besides this one remark.

2022-11-05 16:59 UTC, sjaeckel commented on pb_add.c
> +#include <math.h>
Please apply the following patch to `tompoly.h` instead and use `PB_MIN()` resp. `PB_MAX()`

```
diff --git a/tompoly.h b/tompoly.h
index 646a903..cf79b69 100644
--- a/tompoly.h
+++ b/tompoly.h
@@ -114,2 +114,11 @@ int pb_readraw(pb_poly *a, unsigned char *buf, int len);
 
+/* What follows should be in a private header, but it's fine for now like that. */
+
+#ifndef PB_MIN
+#define PB_MIN(x, y) (((x) < (y)) ? (x) : (y))
+#endif
+#ifndef PB_MAX
+#define PB_MAX(x, y) (((x) > (y)) ? (x) : (y))
+#endif
+
 #endif
```

`used` is an `int` not a `float`, so using `fmin()` resp. `fmax()` doesn't really make sense.

`math.h` is also a pretty fat header file which isn't necessarily available on all platforms.

2022-11-05 23:13 UTC, thesamesam commented on pb_add.c
> +#include <math.h>
No worries! I did audit all the uses of the MAX/MIN here and a float should be fine for what they are, but I agree it's still a bit weird, and the macro is easier. I'll switch to that now, thanks!

2022-11-06 06:23 UTC, thesamesam commented on pb_add.c
> +#include <math.h>
Flipped it over. Thanks!

2022-11-07 15:22 UTC, sjaeckel approved these changes

2022-11-07 15:23 UTC, merged

2022-11-07 16:49 UTC, thesamesam commented
Thank you!